services:
  - type: web_service
    name: bakcon-backend
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    plan: free

  - type: web_service
    name: bakcon-frontend
    env: docker
    branch: main
    dockerfilePath: frontend/Dockerfile
    plan: free
