version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "0.0.0.0,localhost"
    volumes:
      - static_volume:/app/staticfiles

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"

volumes:
  static_volume:
